#!/usr/bin/env bash
#configures Nginx server so that /redirect_me is redirecting t
#The redirectioon must be a “301 Moved Permanently”

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html

default_sites="/etc/nginx/sites-available/default"
location=$(grep -Fn location $default_sites | head -1 | cut -d":" -f1)
location_data="\\\tlocation /redirect_me {\n\t\treturn 301 https://doncod.tech;\n\t}\n\n"
sudo sed -i "${location}i ${location_data}" ${default_sites}
sudo service nginx start
